name: kems_companion
description: KEMS companion app for Home Assistant.
publish_to: none
version: 0.3.2+4

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  web_socket_channel: ^3.0.3
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
